### ISSUE TITLE
RecordType enum value for 'Residential'

### ISSUE THREAD

**Issue by ebrydon** [rombethor/Loqate#4]
Testing this with UK house addresses. The Type for the addresses returned by the Loqate Retrieve API is 'Residential'. This is causing an error when trying to parse into a RetrieveResponseItem as the RecordType enum does not contain 'residential' as a value.

**Comment by rombethor** [comment]
Thanks @ebrydon for getting in touch.

I suspect that the `RecordType` used in `RetrieveResponseItem` shouldn't be the same type as used in `FindItem` so that will need to change.  The documentation is pretty hazy in the matter as it describes `type` as a `string` but in the example it is presented as an integer:

https://www.loqate.com/developers/apis/saas-platform/capture-find-and-retrieve/

I propose to change it to a `string` as a list of valid types has not been provided.

**Comment by ebrydon** [comment]
Hi, thanks for replying so quickly.

in the absence of a definitive list of possible values, having Type as a string does seem like the best solution. Thanks.

**Comment by rombethor** [comment]
I've published v8.2 to nuget.org with this change.
